apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mmvzlwq3t-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mmvzlwq3t-java-springboot-gitops